specific question is fetched with id
sohm22/quizapp pull request #5
Opened 2024-08-12 18:59 UTC by sohm22

added below endpoint
GET /question/<id>

2024-08-13 14:16 UTC, AbhijeetSakhalkar requested changes

2024-08-13 14:16 UTC, AbhijeetSakhalkar commented on src/main/java/com/learning/quizapp/controllers/QuestionController.java
> +    public Optional<Question> getQuestion(@PathVariable int id){
Should not return Optional from controller, if service returns null, controller should return http status code 404

2024-08-13 14:16 UTC, AbhijeetSakhalkar commented on src/main/java/com/learning/quizapp/controllers/QuestionController.java
> +    public Optional<Question> getQuestion(@PathVariable int id){
In general, return  org.springframework.http.ResponseEntity from all controller methods with proper http status code

2024-08-13 14:16 UTC, AbhijeetSakhalkar commented on src/main/java/com/learning/quizapp/services/QuestionService.java
> +    public Optional<Question> getQuestionById(int id) {
Preferably, try to send not found exception from service layer

2024-08-13 14:16 UTC, AbhijeetSakhalkar commented on src/main/java/com/learning/quizapp/controllers/QuestionController.java
> +    public Optional<Question> getQuestion(@PathVariable int id){
In ideal case, you should never return dto objects back to the client. Try for a seperate representation (media) layer which should be packaged separately. Eg, return QuestionMedia instead of Question.

This will help to keep your representation layer separate and hence share it separately if needed to the user service

2024-08-13 14:16 UTC, AbhijeetSakhalkar commented on src/main/java/com/learning/quizapp/services/QuestionService.java
> +    public Optional<Question> getQuestionById(int id) {
I guess, your updateQuestion is not a put operation but a patch operation by definition.
patch = updateIfNotNull
put = update everything

2024-08-13 14:19 UTC, AbhijeetSakhalkar commented
Endpoints according to standards

1. Get all
GET: **/questions**

2. create
POST: **/questions**

3. get, updatem patch and delete by id
GET/PUT/PATCH/DELETE: **/questions/{id}**


[Sample link to refer (which I try to follow)](https://swagger.io/resources/articles/best-practices-in-api-design/)

2024-08-14 01:36 UTC, AbhijeetSakhalkar commented on src/main/java/com/learning/quizapp/services/QuestionService.java
> +    public Optional<Question> getQuestionById(int id) {
1. If the Endpoint is PUT /resources, then yes. You should create a new resource
2. If the endpoint is PUT/resources/{id}, then no. You should not create a new resource

For creating a new resource in point 2, user has provided ID as a path param. This means he expects the given ID to return back. Creating a new resource will create a new ID and will break the assumprion to get / point out resource by ID in the system.

2024-08-14 05:47 UTC, sohm22 commented on src/main/java/com/learning/quizapp/services/QuestionService.java
> +    public Optional<Question> getQuestionById(int id) {
implemented as per recommendations

2024-08-14 14:10 UTC, merged